### ISSUE TITLE
Extremely high memory usage resulting in process termination

### ISSUE THREAD

**Issue by hyling** [DataDog/dd-sdk-ios#178]
### The crash

Writing lots of logs causes memory usage to spike.  On the first wave the memory usage reached 1.2GB.  On the 2nd wave memory usage reached 1.8 GB then iOS terminated process due to memory issue.  Would it be possible to process the logs in smaller sets and/or using @autoreleasepool?

With Datadog OFF:
![image](https://user-images.githubusercontent.com/577992/87252152-e22f7980-c43e-11ea-8fb8-957a208657cb.png)

Datadog ON:
first wave reaches 1.2GB
![image](https://user-images.githubusercontent.com/577992/87252156-e78cc400-c43e-11ea-8807-1f936500e285.png)

then releases memory
![image](https://user-images.githubusercontent.com/577992/87252166-fc695780-c43e-11ea-8a45-086edc18a041.png)

2nd wave : It reached 1.8GB of memory usage then iOS terminated process due to memory issue
![image](https://user-images.githubusercontent.com/577992/87252176-068b5600-c43f-11ea-8def-664097e5bcc2.png)

---

#### Datadog SDK versions:
1.2.2
#### Last stable Datadog SDK version:
NA
#### Volume:
NA not in production
#### OS version:
13.3.1
#### Deployment Target:
iOS 11, iPhone
#### Device version:
iPhone XR
#### Environment:
Memory pressure

**Comment by ncreated** [comment]
Hey @hyling 👋 , thanks for reaching out. Could you give a bit more details on the way you are performing this heavy logging? Is it more a set of synchronous calls to `logger`, or rather a stream of asynchronous log messages?

**Comment by hyling** [comment]
Hi @ncreated.  Thanks for the response.  This is happening on calls to the logger from a background thread.

**Comment by ncreated** [comment]
@hyling I was able to reproduce the issue 👍 and fix it in https://github.com/DataDog/dd-sdk-ios/pull/180. I will let you know once this is confirmed and when we have a new version ready.

**Comment by ncreated** [comment]
Fixed in [`1.2.3`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.2.3) ✅

**Comment by hyling** [comment]
Awesome!  Thanks!

**Comment by hyling** [comment]
@ncreated Unfortunately this doesn't fix the issue for me. Memory usage is still hitting 1.8 GB and the process is still getting terminated.  I'll profile with Instruments and provide more info soon.

**Comment by hyling** [comment]
@ncreated  Here are some Instrument traces of the problem. https://drive.google.com/drive/folders/1PtehtBNHVuE587N98ZgzTYiMge7Rovs4?usp=sharing

For the "datadog ON.trace" within the os_signpost instrument, the processAccBal interval pinned to the bottom is where most of the logging is generated.  "processAccBal" is run on a NSOperationQueue.

**Comment by ncreated** [comment]
@hyling Seems that data upload memory leak was not the core reason of this issue. In the Instruments report you attached, I spotted a bottlenecks in `_FileCache`, which helped me to prepare a benchmark code and reproduce it. I don't know how my benchmark (posted in #185's description) corresponds to your setup, but as I can see some Core Data traces in your report, I assumed that the problem may come from stressing the logger with multiple writing threads and relatively big log messages.

I prepared the fix on [`ncreated/RUMM-610-optimize-memory-usage-when-doing-intensive-logging`](https://github.com/DataDog/dd-sdk-ios/tree/ncreated/RUMM-610-optimize-memory-usage-when-doing-intensive-logging) branch. @hyling is it possible for you to test this branch in your setup before we call it a hotfix 🙏?

Please note, that highly intensive logging may be still problematic due to performance optimizations we do in SDK, i.e. we use a **single thread** for writes and reads to keep the number of threads relatively small. This may be an obvious bottleneck for apps doing massive logging from many threads. What we're looking for in this issue is a sweet spot that would work for everyone. That's why I'd like to start small with the tuning did in #185, before we go further.

**Comment by hyling** [comment]
@ncreated I'd be happy to but I'm having problems building that branch.  I'm getting these errors: 

```
Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/Persistence/Files/File.swift:62:28: error: value of type 'FileHandle' has no member 'seekToEnd'
try fileHandle.seekToEnd()
~~~~~~~~~~ ^~~~~~~~~
Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/Persistence/Files/File.swift:63:33: error: extraneous argument label 'contentsOf:' in call
try fileHandle.write(contentsOf: data)
^~~~~~~~~~~~~

Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/Persistence/Files/File.swift:94:35: error: value of type 'FileHandle' has no member 'readToEnd'
return try fileHandle.readToEnd() ?? Data()
~~~~~~~~~~ ^~~~~~~~~
Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/AutoInstrumentation/URLSessionSwizzler.swift:68:13: error: ambiguous reference to member 'swizzle(using:)'
swizzle(method) { currentTypedImp -> BlockIMP in
^~~~~~~
Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/AutoInstrumentation/URLSessionSwizzler.swift:65:14: note: found this candidate
func swizzle(using interceptor: @escaping RequestInterceptor) {
^
Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/AutoInstrumentation/MethodSwizzler.swift:63:10: note: found this candidate
func swizzle(
^
Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/AutoInstrumentation/URLSessionSwizzler.swift:109:13: error: ambiguous reference to member 'swizzle(using:)'
self.swizzle(self.method) { typedCurrentImp -> BlockIMP in
^~~~
Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/AutoInstrumentation/URLSessionSwizzler.swift:106:14: note: found this candidate
func swizzle(using interceptor: @escaping RequestInterceptor) {
^
Carthage/Checkouts/dd-sdk-ios/Sources/Datadog/Core/AutoInstrumentation/MethodSwizzler.swift:63:10: note: found this candidate
func swizzle(
^
```

**Comment by ncreated** [comment]
@hyling sorry, I forgot to rebase this branch onto `1.2.3` tag. Now it should be fine 🙌 (please note: I did a force push, so you may need to clear Carthage cache 🤔).

**Comment by hyling** [comment]
@ncreated It builds fine now.  I'm on Xcode 11.3 targeting iOS 11.  I'm hoping to upgrade as soon as I'm at a good stopping point with this project.  That fixes the issue! 🎉  It peaks at 208 MB now and CPU utilization is much improved too!  I shared a trace of the fixed version in case you're interested.  Thanks for the fast response!

https://drive.google.com/file/d/1HEhmIOpyjzvn_cxAGYJO4JqgDv6CGshg/view?usp=sharing

**Comment by ncreated** [comment]
Yay, glad it helps @hyling . Thanks for follow up and the last trace - I can see the `_FileCache` is no longer an issue there. We will deploy the `1.2.4` hotfix tomorrow 👌.
