### ISSUE TITLE
Build error in Xcode 16 / iOS18

### ISSUE THREAD

**Issue by pixelmatrix** [DataDog/dd-sdk-ios#1892]
### Describe the bug

Getting the following error when trying to build my app in Xcode 16 / iOS 18.

```
Type 'UIApplication' does not conform to protocol 'UIKitAppBackgroundTaskCoordinator'
```

```
Candidate has non-matching type '((@MainActor () -> Void)?) -> UIBackgroundTaskIdentifier'
```

It looks like `@MainActor` was added to `beginBackgroundTask(expirationHandler:)`, causing automatic conformance to fail.

### Reproduction steps

- Install Xcode 16
- Integrate Datadog iOS SDK in an app
- Build the app and look at the errors

### Affected SDK versions

2.8.1

### Latest working SDK version

N/A

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

SPM

### Xcode Version

16

### Swift Version

5.9

### Deployment Target

iOS 17, iPhone

**Comment by BrentMifsud** [comment]
seeing this as well

**Comment by maciejburda** [comment]
Thank you for reporting and pointing out in a right direction! 🙇

Fix has been merged, and will be released in the upcoming release.

**Comment by marshall86** [comment]
i just upgraded xcode and i got the same error, when are you going to release the fix?

**Comment by annu18priya** [comment]
I upgraded to Xcode 16 and trying to launch the app on iOS 18 Simulator. I am getting this error _Type 'UIApplication' does not conform to protocol 'UIApplicationProtocol'_ in multiple part of my project. By when this can be fixed.

**Comment by marshall86** [comment]
i upgraded to Xcode16 to but it has some issues, i had to downgrade to 15.4 for now. To run 15.4 on the latest MacOS version you need to run xcode from the terminal...

**Comment by maciejburda** [comment]
@marshall86 Could you please provide more details and ideally a sample project that reproduces this issue?

We have some internal projects and they run without a problem on Xcode16 / iOS18.

**Comment by marshall86** [comment]
> @marshall86 Could you please provide more details and ideally a sample project that reproduces this issue?
> 
> We have some internal projects and they run without a problem on Xcode16 / iOS18.

I managed to make it work by removing the Podfile.lock and then running ionic cap sync ios, because the issue was related to Jumio who uses your library inside their package.

**Comment by iOSLearner-dev** [comment]
> I upgraded to Xcode 16 and trying to launch the app on iOS 18 Simulator. I am getting this error **_Type 'UIApplication' does not conform to protocol 'UIApplicationProtocol'_** in multiple part of my project. By when this can be fixed.?

Above reported issue has been fixed. Apple has updated some of the UIApplicationProtocol methods which needs to be updated in code level.

**Comment by Qamar-VD** [comment]
Can some please share that above issue 'UIApplication' does not conform to protocol 'UIApplicationProtocol'  for Xcode16 and iOS18 has been resolved for them ? If yes then please what are the exact steps to be followed to resolve this ? Thanks

**Comment by shagedorn** [comment]
For us, this was resolved as per https://github.com/DataDog/dd-sdk-ios/releases/tag/2.11.1. Our app builds & runs successfully on Xcode 16.

**Comment by MayankStx** [comment]
Facing the issue still on DataDog 2.19.1 with Xcode 16.1 on Mac OS 15.1. Can someone help?

**Comment by maciejburda** [comment]
@MayankStx Are you sure you are using correct SDK? We haven't released `2.19.1` yet.

Normally this issue should be resolved. I advice to clean the project and rebuild from scratch.

**Comment by mfathy** [comment]
@MayankStx I was facing the same issue on `2.19.1` and I resolved it by updating the `dd` to `2.22.0`
