### ISSUE TITLE
Carthage Compilation Error: 'module.modulemap' should be inside the 'include' directory

### ISSUE THREAD

**Issue by joeydong** [DataDog/dd-sdk-ios#71]
**Describe what happened**

Hi, I'm trying to install the latest release dd-sdk-ios 1.0.1 using Carthage 0.34.0 and Xcode 11.3.1 but this dependency fails to compile with this error:

```
$ /usr/bin/xcrun xcodebuild -workspace /Carthage/Checkouts/dd-sdk-ios/instrumented-tests/Integration/Integration.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list
Build settings from command line:
    CARTHAGE = YES
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO

Resolve Package Graph

Resolved source packages:
  dd-sdk-ios: /Carthage/Checkouts/dd-sdk-ios
  HTTPServerMock: /Carthage/Checkouts/dd-sdk-ios/instrumented-tests/http-server-mock

xcodebuild: error: Could not resolve package dependencies:
  package has unsupported layout; modulemap '/Carthage/Checkouts/dd-sdk-ios/Datadog/DatadogPrivate/module.modulemap' should be inside the 'include' directory
```

I got this xcrun command from the failed Carthage output:

```
A shell task (/usr/bin/xcrun xcodebuild -workspace /Carthage/Checkouts/dd-sdk-ios/instrumented-tests/Integration/Integration.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Could not resolve package dependencies:
  package has unsupported layout; modulemap '/Carthage/Checkouts/dd-sdk-ios/Datadog/DatadogPrivate/module.modulemap' should be inside the 'include' directory
```

Any ideas?

**Steps to reproduce the issue:**

Looks like I can reproduce this in Xcode 11.3.1 by:

1. Clone this repo
1. Open `/dd-sdk-ios/examples/iOS-app-example-spm/iOS-app-example-spm.xcodeproj`
1. Cmd + B

<img width="1895" alt="Screen Shot 2020-04-07 at 5 31 51 PM" src="https://user-images.githubusercontent.com/434294/78731859-c6737f00-78f5-11ea-92c5-5e8c7074f511.png">

The compilation works fine in Xcode 11.4.0, somewhat surprisingly, but 🤷‍♂ :

<img width="1895" alt="Screen Shot 2020-04-07 at 5 38 24 PM" src="https://user-images.githubusercontent.com/434294/78732136-a98b7b80-78f6-11ea-898c-53aa4717f6ae.png">

**Expected behaviour:**
📝

**Actual behaviour:**
📝

**Additional context**
 - OS version and device model
 - Datadog SDK version

An explanation of what might cause the bug and/or how it can be fixed:

Removing the empty `/Datadog/DatadogPrivate/module.modulemap` file seems to satisfy the compiler and fixes the build. Not sure what the implications of this are, though, perhaps an undesirable one is auto-generated.

**Comment by ncreated** [comment]
Hey @joeydong 👋. Thank you for reporting this and so much details. I can reproduce it on `Xcode 11.3.1 (11C505)`. **We're working on the fix.**

As a workaround - it works fine on `Xcode 11.4 (11E146)`, but I understand that this might be not possible to everyone.

**Comment by ncreated** [comment]
Solved in #73 and [1.0.2](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.0.2) is available. Thanks for all the details @joeydong 🏅

**Comment by 00FA9A** [comment]
when I pull 1.0.2 and run `carthage build --no-skip-current` I still get 
```
A shell task (/usr/bin/xcrun xcodebuild -project .../dd-sdk-ios/dependency-manager-tests/spm/SPMProject.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'SPMProject.xcodeproj' from folder '.../dd-sdk-ios/dependency-manager-tests/spm'.
	Reason: Project .../dd-sdk-ios/dependency-manager-tests/spm/SPMProject.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```

I feel like im missing something...

**Comment by ncreated** [comment]
@00FA9A Please ensure that `Carthage/Checkout/dd-sdk-ios` does not contain old revision of our repo:
```
$ rm -rf Carthage/Checkouts/dd-sdk-ios/
```
Seems that Carthage doesn't remove it entirely before clone and `SPMProject.xcodeproj` which was removed in recent version of our SDK is still there.

**Comment by 00FA9A** [comment]
@ncreated thanks for pointing out the local checkout folder. I was clearing up global Carthage cache, but forgot to clean this up too

**Comment by 00FA9A** [comment]
@ncreated we get `Missing required module '_Datadog_Private'` error on builds if `Carthage/Checkouts/dd-sdk-ios/Datadog/DatadogPrivate/include/module.modulemap` is not present

we rely on CarthageCache for our dependencies, which just caches Builds folder. basically, we are unable to build on CI or whenever actual checkout of DataDog is not present

**Comment by 00FA9A** [comment]
@ncreated is the above expected or should a separate issue be filed?

I've been able to repro easily by including a Carthage dependency in a simple project, removing `Carthage/Checkouts/dd-sdk-ios/Datadog/DatadogPrivate` and trying to build

**Comment by ncreated** [comment]
Hey @00FA9A 👋. This sounds like a separate issue as vanilla Carthage installation works fine. I just opened #77 - we jump on this next 💪.
